In [22]:
import pandas as pd
import seaborn
import numpy as np 
import matplotlib.pyplot as mtp
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler  
from sklearn.linear_model import LogisticRegression 



In [23]:
user_data=pd.read_csv('Dataset1.csv')
y=user_data.Discontinued


In [24]:
features=['gender','SeniorCitizen','Partner','Dependents','tenure','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','MonthlyCharges','TotalCharges']
non_features=["Discontinued"]



In [25]:
x=user_data.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]].values
y=user_data.iloc[:,19].values
y

array([0, 0, 1, ..., 0, 1, 0])

In [26]:
#split into validation and training data
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0) 
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
 #feature Scaling    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)  

In [28]:
#Fitting Logistic Regression to the training set  
 
classifier= LogisticRegression(solver='saga',max_iter=1000,random_state=1)  
classifier.fit(x_train, y_train)  

LogisticRegression(max_iter=1000, random_state=1, solver='saga')

In [29]:
y_pred= classifier.predict(x_test)  
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [30]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test,y_pred)  
cm

array([[1157,  141],
       [ 220,  243]])

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)


0.7950028392958546